### ISSUE TITLE
Not loading tkinter module

### ISSUE THREAD

**Issue by ThePieBandit** [JackMcKew/pyinstaller-action-linux#2]
**Describe the bug**
I have a python script that uses tkinter to provide a simple file dialog and message box. When I test and build locally with pyinstaller to generate the spec file, the executable works fine. building in the github action succeeds, but the executable created doesn't work, giving the error: 
    
```
Traceback (most recent call last):
  File "tcg-to-deckbox.py", line 6, in <module>
  File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "tkinter/__init__.py", line 36, in <module>
ModuleNotFoundError: No module named '_tkinter'
```

**To Reproduce**
I ran with the following github action flow
```

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# additionally allows a manual trigger via workflow_dispatch
on:
  workflow_dispatch:
    types: ManualUpdate
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: PyInstaller Linux
      uses: JackMcKew/pyinstaller-action-linux@0.1.3
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: tcg-to-deckbox
        path: src/dist/linux
```

[successful.log](https://github.com/JackMcKew/pyinstaller-action-linux/files/5139811/successful.log)
[failure_logs_17.zip](https://github.com/JackMcKew/pyinstaller-action-linux/files/5139818/failure_logs_17.zip)

As you'll note from the attached logs, the one where the executable functions has the line `3120 INFO: Loading module hook 'hook-_tkinter.py' from '/home/rspremulli/.local/lib/python3.6/site-packages/PyInstaller/hooks'...` while the github action doesn't. Is there some issue why it won't load the tkinter module?
