### ISSUE TITLE
What if my source code is the root of the repo?

### ISSUE THREAD

**Issue by TheTechRobo** [JackMcKew/pyinstaller-action-linux#5]
Do I use "." as the source code path or...?

I know it's not great practice, but I'm not redoing my file structure; it's bound to break something.

**Comment by JackMcKew** [comment]
Using the path as `.` _should_ work without any issues, let me know how it goes

**Comment by TheTechRobo** [comment]
I'll try it if I find the time.

**Comment by JacobMillner** [comment]
I just tested this out and it does work but make sure you change `actions/upload-artifact@v2` path as well!

```
- uses: actions/upload-artifact@v2
        with:
          name: package-name
          path: ./dist/linux
```
